### PR TITLE
Native char and filter

### PR DESCRIPTION
**Pull request by dondoco7**
This is need fix.
Proposal PR.

- Webpack update
- Add filter
- return Unicode Charactor

### CODE REVIEW

**Comment by dondoco7** [comment]
Sorry to be confusing.

In our product, I want the emoji Picker to return the character code of unicode? Instead of the colon string.

And I want an API to limit pictograms displayed on the palette.

This code is actually used by our Product.

If you can add functionality, please refer to it.

**Comment by dondoco7** [comment]
Is it no resistance to prepare an option to receive emoji in Unicode?
If that is not enough, I will withdraw this PR.

The filter function is necessary because there are pictograms that can not be displayed by OS / brower.
(It will not be necessary if it is a colon character.)

We think that this function should be managed with an official repository if possible.
Please tell me if there is anything we can do.

**Comment by RobertMenke** [comment]
@dondoco7 I'm going to add a method that let's you manipulate the emoji before it gets inserted into the input. Are you planning on only supporting Mac OS users? Windows operating systems do not support emoji characters, so inserting unicode only would be a bad experience for them which is why I've followed Slack's approach of using colons for textareas. If you can use `contenteditable` elements this library can guarantee that they always see the emoji characters.

**Comment by dondoco7** [comment]
Thank you for your reply.

We also support Windows.
Although the color is not attached. .

Some pictograms can not be displayed with some versions of Unicode, but they have been removed with the Fitlter function.

I understand the policy to handle only colon strings.
I thought it would be so, but I tried sending it just in case.

Thank you for your response.

**Pull request closed without merging**
